# Generated by Django 4.2 on 2025-12-30 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('page_url', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог посещения',
                'verbose_name_plural': 'Логи посещений',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Выручка')),
                ('total_orders', models.IntegerField(default=0, verbose_name='Количество заказов')),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Средний чек')),
                ('total_products', models.IntegerField(default=0, verbose_name='Всего товаров')),
                ('new_products', models.IntegerField(default=0, verbose_name='Новых товаров')),
                ('new_users', models.IntegerField(default=0, verbose_name='Новых пользователей')),
                ('total_users', models.IntegerField(default=0, verbose_name='Всего пользователей')),
                ('conversion_rate', models.FloatField(default=0, verbose_name='Конверсия')),
                ('cart_abandonment_rate', models.FloatField(default=0, verbose_name='Брошенные корзины')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('top_selling_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Топ товар')),
            ],
            options={
                'verbose_name': 'Метрика дашборда',
                'verbose_name_plural': 'Метрики дашборда',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SaleAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_sales', models.IntegerField(default=0, verbose_name='Продажи (шт)')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Выручка')),
                ('average_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Средняя цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'verbose_name': 'Аналитика продаж',
                'verbose_name_plural': 'Аналитика продаж',
                'ordering': ['-date', 'category'],
                'unique_together': {('category', 'date')},
            },
        ),
    ]
