# Generated by Django 6.0 on 2025-12-31 14:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('short_description', models.CharField(max_length=300, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Описание')),
                ('detailed_description', models.TextField(blank=True, verbose_name='Подробное описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена со скидкой')),
                ('file', models.FileField(upload_to='products/files/', verbose_name='Файл товара')),
                ('preview_image', models.ImageField(upload_to='products/previews/', verbose_name='Превью')),
                ('additional_images', models.ImageField(blank=True, null=True, upload_to='products/additional/', verbose_name='Дополнительные изображения')),
                ('product_type', models.CharField(choices=[('template', 'Шаблон сайта'), ('graphics', 'Графика'), ('ebook', 'Электронная книга'), ('software', 'Программное обеспечение'), ('course', 'Курс'), ('music', 'Музыка'), ('photo', 'Фотографии'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип товара')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='Теги')),
                ('file_size', models.CharField(blank=True, max_length=50, verbose_name='Размер файла')),
                ('file_format', models.CharField(blank=True, max_length=20, verbose_name='Формат файла')),
                ('version', models.CharField(blank=True, max_length=20, verbose_name='Версия')),
                ('compatibility', models.CharField(blank=True, max_length=200, verbose_name='Совместимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('sales_count', models.IntegerField(default=0, verbose_name='Количество продаж')),
                ('view_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название характеристики')),
                ('value', models.CharField(max_length=200, verbose_name='Значение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products.product')),
            ],
            options={
                'verbose_name': 'Характеристика товара',
                'verbose_name_plural': 'Характеристики товаров',
                'ordering': ['order'],
            },
        ),
    ]
